### ISSUE TITLE
konteks spellcheck

### ISSUE THREAD

**Issue by lantip** [ivanlanin/aglutinasi#1]
mantap uda! 
tapi ini sepertinya sudah terlingkupi ketika kita bikin stemmer ya? yang jadi masalah kemudian ketika bicara lingkup salah tik, terutama aturan penulisan (disambung atau tidak).

mungkinkah kita bikin rumusnya tanpa harus men-train mesin terlebih dahulu untuk memahami struktur bahasa indonesia?

**Comment by ivanlanin** [comment]
Oke. Kucoba rumuskan.

**Comment by lantip** [comment]
_klik suka_

**Comment by ivanlanin** [comment]
Begini alurnya?

![alur](https://cloud.githubusercontent.com/assets/15313/11918115/8b4e6d2e-a756-11e5-90f1-9a826741f796.jpg)

**Comment by lantip** [comment]
tepat sekali uda! :dancer:

**Comment by ivanlanin** [comment]
Baiklah. Kalau begitu, lebih baik dikembangkan dari "Pengakar" :smile: Nanti kucoba.

**Comment by lantip** [comment]
coba uda periksa [speller.py](https://github.com/ardwort/ardspellchecker/blob/master/speller.py) di ardspellchecker. nah, sampai bagian mengakarkan itu sudah ada, tinggal pemeriksaan pola saja. 

menurutku ini mestinya di luar pengakar, karena bukan valid/tidaknya akar katanya, tetapi lebih ke penulisannya :D

**Comment by ivanlanin** [comment]
Okesip. Kulanjutkan setelah Rabu, ya. Ngurusin kerjaan kantor dulu.

**Comment by lantip** [comment]
siap! terimakasih sekali uda :D _menjura_
